version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/flask-app

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ubuntu
  Install:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
