version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Building Flask App...
      - docker build -t flask-app .
  post_build:
    commands:
      - echo Build completed successfully.
